groups_config:
  priority_list:
    - http://www.w3.org/2000/01/rdf-schema#subClassOf
    - http://www.w3.org/2000/01/rdf-schema#seeAlso
  groups:
    - name: Glossary
      items:
        - 'http://www.w3.org/2000/01/rdf-schema#label'
        - 'http://www.w3.org/2004/02/skos/core#prefLabel'
        - 'http://www.w3.org/2004/02/skos/core#altLabel'
        - 'https://www.omg.org/spec/Commons/AnnotationVocabulary/synonym'
        - 'https://www.omg.org/spec/Commons/AnnotationVocabulary/symbol'
        - 'http://www.w3.org/2004/02/skos/core#definition'
        - 'http://purl.org/dc/terms/source'
        - 'https://www.omg.org/spec/Commons/AnnotationVocabulary/directSource'
        - 'https://www.omg.org/spec/Commons/AnnotationVocabulary/adaptedFrom'
        - 'http://www.w3.org/2004/02/skos/core#example'
        - 'http://www.w3.org/2004/02/skos/core#note'
        - 'http://www.w3.org/2004/02/skos/core#scopeNote'
        - 'http://www.w3.org/2004/02/skos/core#editorialNote'
        - 'https://www.omg.org/spec/Commons/AnnotationVocabulary/explanatoryNote'
        - 'https://www.omg.org/spec/Commons/AnnotationVocabulary/usageNote'
        - 'http://purl.org/dc/terms/title'
        - 'http://purl.org/dc/elements/1.1/identifier'
        - 'http://purl.org/dc/terms/abstract'
        - 'http://purl.org/dc/terms/description'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/explanatoryNote'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/abbreviation'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/firstOrderLogicAxiom'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/naturalLanguageDefinition'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/semiFormalNaturalLanguageAxiom'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/acronym'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/firstOrderLogicAxiom'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/adaptedFrom'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/counterExample'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/logicDefinition'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/firstOrderLogicDefinition'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/semiFormalNaturalLanguageDefinition'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/subjectMatterExpertExplanation'
        - 'https://spec.industrialontologies.org/ontology/core/Core/ActionSpecification'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/maintainer'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/directSource'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/excerptedFrom'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/maturity'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/symbol'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/synonym'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/logicAxiom'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/primitiveRationale'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/usageNote'

    - name: This ontology contains
      items:
        - '@viewer.internal.clazz'
        - '@viewer.external.clazz'
        - '@viewer.internal.objectProperty'
        - '@viewer.external.objectProperty'
        - '@viewer.internal.dataProperty'
        - '@viewer.external.dataProperty'
        - '@viewer.internal.instance'
        - '@viewer.external.instance'
        - '@viewer.internal.annotationProperty'
        - '@viewer.external.annotationProperty'
        - '@viewer.internal.dataType'
        - '@viewer.external.dataType'
    - name: Ontological characteristic
      items:
        - '@viewer.function.direct_sub_data_property'
        - '@viewer.function.direct_sub_object_property'
        - '@viewer.function.direct_sub_annotation_property'
        - '@viewer.function.direct_subclasses'
        - '@viewer.function.instances'
        - '@viewer.axiom.EquivalentClasses'
        - '@viewer.axiom.SubClassOf'
        - '@viewer.function.anonymous_ancestor'
        - '@viewer.axiom.DisjointClasses'
        - '@viewer.axiom.ClassAssertion'
        - '@viewer.axiom.SameIndividual'
        - '@viewer.axiom.ObjectPropertyAssertion'
        - '@viewer.axiom.DataPropertyAssertion'
        - '@viewer.axiom.SubObjectPropertyOf'
        - '@viewer.axiom.SubDataPropertyOf'
        - '@viewer.axiom.SubAnnotationPropertyOf'
        - '@viewer.axiom.EquivalentObjectProperties'
        - '@viewer.axiom.EquivalentDataProperties'
        - '@viewer.axiom.ObjectPropertyDomain'
        - '@viewer.axiom.DataPropertyDomain'
        - '@viewer.axiom.ObjectPropertyRange'
        - '@viewer.axiom.FunctionalObjectProperty'
        - '@viewer.axiom.DataPropertyRange'
        - '@viewer.axiom.AnnotationPropertyDomain'
        - '@viewer.axiom.AnnotationPropertyRangeOf'
        - '@viewer.axiom.InverseObjectProperties'
        - '@viewer.function.axiom_object_property'
        - '@viewer.axiom.TransitiveObjectProperty'
        - 'http://www.w3.org/2002/07/owl#deprecated'
        - 'http://purl.org/dc/terms/hasPart'
    - name: Meta-information
      items:
        - 'http://purl.org/dc/terms/creator'
        - 'http://purl.org/dc/terms/license'
        - 'https://www.omg.org/spec/Commons/AnnotationVocabulary/copyright'
        - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/copyright'
        - 'http://purl.org/dc/terms/contributor'
        - 'http://purl.org/dc/terms/issued'
        - 'http://www.w3.org/2004/02/skos/core#changeNote'
        - 'http://www.w3.org/2004/02/skos/core#note'
        - 'http://www.w3.org/2000/01/rdf-schema#comment'
        - 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
        - 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
        - 'http://www.w3.org/2004/02/skos/core#historyNote'
        - 'http://purl.org/dc/terms/hasVersion'
    - name: Usage
      items:
        - '@viewer.function.usage_classes'
